# Generated by Django 3.2.3 on 2021-07-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentregistration',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('photo', models.FileField(upload_to='student_images')),
                ('date_of_reg', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
